setlocal foldenable
setlocal foldlevel=1
setlocal foldmethod=syntax
setlocal smarttab
setlocal linebreak
setlocal expandtab
setlocal shiftwidth=4
setlocal tabstop=4
setlocal textwidth=79
setlocal colorcolumn=80
