#!/bin/bash

set -eu

_log() {
    echo "shellcheck: $*"
}

if [[ ! -f "$(command -v shellcheck)" ]]; then
    _log "skipping: shellcheck not found"
fi

function test_file() {
    local -r file="${1}"
    if [ -f "${file}" ] && head -1 "${file}" | grep -qE '^#!/bin/(ba|)sh$'; then
        shellcheck "${file}"
    fi
}

case "${1:-}" in
--about)
    echo "shellcheck sh or bash shell scripts."
    ;;
'')
    git diff-index --cached --name-only HEAD |
        while read -r file; do
            test_file "${file}"
        done
    ;;
esac
