#!/bin/bash

set -eu

_log() {
    echo "shfmt: $*"
}

if [[ ! -f "$(command -v shfmt)" ]]; then
    _log "skipping: shfmt not found"
fi

function test_file() {
    shfmt -i 4 -d "${1}"
}

case "${1:-}" in
--about)
    echo "shfmt sh or bash shell scripts."
    ;;
*)
    git ls-sh-scripts "$(git diff-index --cached --name-only HEAD)" |
        while read -r file; do
            test_file "${file}"
        done
    ;;
esac
