#!/bin/bash

set -eu

_log() {
    echo "shfmt: $*"
}

if [[ ! -f "$(command -v shfmt)" ]]; then
    _log "skipping: shfmt not found"
fi

function test_file() {
    local -r file="${1}"
    if [ -f "${file}" ] && head -1 "${file}" | grep -qE '^#!/bin/(ba|)sh$'; then
        shfmt -i 4 -d "${file}"
    fi
}

case "${1:-}" in
--about)
    echo "shfmt sh or bash shell scripts."
    ;;
*)
    git diff-index --cached --name-only HEAD |
        while read -r file; do
            test_file "${file}"
        done
    ;;
esac
