# See https://pre-commit.com/#usage
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/jazzband/pip-tools
  rev: 6.8.0
  hooks:
    - id: pip-compile
      files: ^python/requirements.(in|txt)$
      args: [python/requirements.in]
- repo: local
  hooks:
    - id: shfmt
      name: shfmt
      minimum_pre_commit_version: 2.4.0
      language: golang
      additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.3.1]
      entry: shfmt
      args: [-w, -s, -i, "4"]
      types: [shell]
