dist: xenial
language: python
python: 3.7

cache:
  pip: true

env:
  matrix:
    - LINT=vint-errors
    - LINT=vint
    - LINT=shellcheck

matrix:
  allow_failures:
    - env: LINT=vint

install:
  - |
    if [ "${LINT#vint}" != "$LINT" ]; then
      pip install vim-vint
    fi

script:
  - bin/dot --lint
