language: python

cache:
  pip: true

env:
  matrix:
    - LINT=vint-errors
    - LINT=vint
    - LINT=shellcheck

matrix:
  allow_failures:
    - env: LINT=vint

install:
  - |
    [ "${LINT#vint}" != "$LINT" ] && \
      virtualenv /tmp/vint && \
      source /tmp/vint/bin/activate && \
      pip install vim-vint enum34 pathlib typing
script:
  - make lint
