dist: xenial
cache:
  pip: true

matrix:
  include:
    - language: python
      python: 3.7
      before_script: |
        pip install vim-vint
      script:
        - ./ci/lint.sh vim
    - language: go
      go: 1.13.x
      script:
        - GOBIN="$(pwd)/tools" go install mvdan.cc/sh/v3/cmd/shfmt
        - ./ci/lint.sh sh
