dist: xenial
cache:
  pip: true

matrix:
  include:
    - language: python
      python: 3.7
      env: LINT=vint
      before_script: |
        pip install vim-vint
      script:
        - bin/dotr --lint
    - language: python
      python: 3.7
      env: LINT=vint-errors
      before_script: |
        pip install vim-vint
      script:
        - bin/dotr --lint
    - language: go
      go: 1.13.x
      env: LINT=shellcheck
      script:
        - GOBIN="$(pwd)/tools" go install mvdan.cc/sh/v3/cmd/shfmt
        - bin/dotr --lint
  allow_failures:
    - env: LINT=vint
