#!/bin/bash

set -eu

_log() {
    echo "shellcheck: $*"
}

if [[ ! -f "$(command -v shellcheck)" ]]; then
    _log "skipping: shellcheck not found"
fi

function test_file() {
    shellcheck "${1}"
}

case "${1:-}" in
--about)
    echo "shellcheck sh or bash shell scripts."
    ;;
'')
    git ls-sh-scripts "$(git diff-index --cached --name-only HEAD)" |
        while read -r file; do
            test_file "${file}"
        done
    ;;
esac
