#!/bin/bash

readonly _ignored=(
    neovim/nvim/plugin/packer_compiled.vim
)

set -eu

_log() {
    echo "vimlparser: $*"
}

if [[ ! -f "$(command -v vimlparser)" ]]; then
    _log "skipping: vimlparser not found"
fi

function test_file() {
    local -r file="${1}"
    if [[ ! -f "${file}" || " ${_ignored[*]} " == *" $file "* ]]; then
        return
    fi

    vimlparser "${file}" >/dev/null
}

if [[ "${1:-}" == --about ]]; then
    echo "vint sh or bash shell scripts."
    return
fi

git diff-index --cached --name-only HEAD |
    grep -E "\.vim$" |
    while read -r file; do test_file "$file"; done
