#!/bin/bash

set -eu

_log() {
    echo "vimlparser: $*"
}

if [[ ! -f "$(command -v vimlparser)" ]]; then
    _log "skipping: vimlparser not found"
fi

function test_file() {
    local -r file="${1}"
    if [ -f "${file}" ]; then
        vimlparser "${file}" >/dev/null
    fi
}

case "${1:-}" in
--about)
    echo "vint sh or bash shell scripts."
    ;;
*)
    git diff-index --cached --name-only HEAD |
        grep -E "\.vim$" |
        while read -r file; do
            test_file "${file}"
        done
    ;;
esac
