# See 'man i3status-rs'
[theme]
theme = "slick"
[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:20) $play $next |}"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "$icon $5m [5m]"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "$icon $percentage $time"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
alert = 1
warning = 2
format = "$icon /:$available"

[[block]]
block = "disk_space"
path = "/home/"
info_type = "available"
alert_unit = "GB"
alert = 5
warning = 20
format = "/home/:$available"

[[block]]
block = "net"
format = " $icon {$signal_strength [$ssid]$frequency|wired} [$device]"

[[block]]
block = "time"
interval = 60
timezone = "Asia/Tokyo"
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M') "
short = " $icon $timestamp.datetime(f:%R) "
