#!/bin/bash
set -euo pipefail

[[ -z "${DOTFILES_ROOT}" ]] && DOTFILES_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export DOTFILES_ROOT
cd "$(dirname "$0")/.."

print_help() {
    cat <<EOF
bootstrap -- dotfiles management

Usage: script/bootstrap [options]

Options:
  -h, --help      Show this help message and exit
EOF
}

while test $# -gt 0; do
    case "$1" in
    "-h" | "--help")
        print_help
        exit
        ;;
    *)
        echo "Invalid option: $1"
        print_help
        exit
        ;;
    esac
    shift
done

set -oe pipefail

# shellcheck source=/dev/null
source script/logging.sh

echo ''

setup_gitconfig() {
    [ -f git/dot-gitconfig ] && return

    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]; then
        git_credential='osxkeychain'
    fi

    user ' - Email to use for commits by default?'
    read -re git_authoremail

    sed -e "s|AUTHOREMAIL|$git_authoremail|g" \
        -e "s|GIT_CREDENTIAL_HELPER|$git_credential|g" \
        git/gitconfig.tmpl >git/dot-gitconfig.local

    ok 'gitconfig'
}

setup_gitconfig

info "installing dependencies"
export DOTFILES="$DOTFILES_ROOT"
if "$DOTFILES_ROOT/script/install" 2>&1 | tee /tmp/dotfiles-dot; then
    ok "dependencies installed"
else
    fail "error installing dependencies"
fi

${DOTFILES}/bin/restow

info 'All setup!'
