#!/bin/bash
#
# bootstrap installs things.

[[ -z "${DOTFILES_ROOT}" ]] && DOTFILES_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export DOTFILES_ROOT
cd "$(dirname "$0")/.."

print_help() {
  cat <<EOF
bootstrap -- dotfiles management

Usage: script/bootstrap [options]

Options:
  -o, --overwrite Replace the existing dotfiles with dotfile symlinks
  -b, --backup    Backup the existing dotfiles before creating dotfile symlinks
  -s, --skip      Skip the existing dotfiles
  -h, --help      Show this help message and exit
EOF
}

while test $# -gt 0; do
  case "$1" in
    "-h"|"--help") print_help; exit ;;
    "-o"|"--overwrite" ) OVERWRITE_ALL=true;;
    "-b"|"--backup") BACKUP_ALL=true;;
    *)
      echo "Invalid option: $1"
      print_help
      exit
      ;;
  esac
  shift
done

set -oe pipefail

# shellcheck source=/dev/null
source script/logging.sh

echo ''

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    gitconfig_main=git/gitconfig.main

    user ' - What is your author name?'
    read -re git_authorname
    user ' - What is your author email?'
    read -re git_authoremail

    sed -e "s|AUTHORNAME|$git_authorname|g" \
        -e "s|AUTHOREMAIL|$git_authoremail|g" \
        -e "s|GIT_CREDENTIAL_HELPER|$git_credential|g" \
        -e "s|GITCONFIG_MAIN|$gitconfig_main|g" \
        git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

install_dotfiles () {
  info 'installing dotfiles'
  cmd=(script/link_dotfile)
  [[ ${OVERWRITE_ALL} == "true" ]] && cmd=("${cmd[@]}" --overwrite)
  [[ ${BACKUP_ALL} == "true" ]] && cmd=("${cmd[@]}" --backup)
  find . -maxdepth 2 -name '*.symlink' -exec "${cmd[@]}" {} \;
  find . -maxdepth 2 -name '*.xdg' -exec "${cmd[@]}" {} \;
}

setup_gitconfig
install_dotfiles

info "installing dependencies"
export DOTFILES="$DOTFILES_ROOT"
if "$DOTFILES_ROOT/script/install" 2>&1 | tee /tmp/dotfiles-dot
then
  success "dependencies installed"
else
  fail "error installing dependencies"
fi

info 'All setup!'
