#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")/.."
find . -name install.sh \
  -exec printf "  [ \033[00;34m..\033[0m ] Running %s\n" {} \; \
  -exec "$SHELL" -c {} \; \
  -exec printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" {} \;
