#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

export DOTFILES_ROOT="${DOTFILES_ROOT:-$(command -v "$0" | xargs dirname)/..}"
cd "${DOTFILES_ROOT}"
# shellcheck source=./script/logging.sh
source "./script/logging.sh"

for f in $(git ls-files | grep -E "install.sh$"); do
  "$SHELL" -c "$f"
  success "$f"
done
