#!/bin/bash

set -oe pipefail

grepbang() {
  rg -l --no-ignore "^#!$1" ||
    grep -rl --exclude-dir=.git "^#\!$1" . || (
      echo "failed to get files" && exit 1)
}

lintsh() {
  files=$({
    grepbang ".*/sh"
    grepbang ".*/bash"
    grepbang "/usr/bin/env bash"
    grepbang "/usr/bin/env sh"
  })
  print_run "shell" "$files"
  run "$files" shellcheck
}

lintvim() {
  files=$(fd -e vim ||
    find . -name "*\.vim" || (
      echo "failed to get files" && exit 1))
  print_run "vim" "$files"
  run "$files" vint "$@"
}

print_run() {
  echo -e "linting $1 files:"
  echo -e "$2" | sort -u | sed "s|^| » |"
  echo
}

run() {
  files=$1; shift
  echo "$files" | sort -u | xargs "$@"
}

case "${LINT:-all}" in
  "vint")
      lintvim
      ;;
  "vint-errors")
      lintvim --error
      ;;
  "shellcheck")
      lintsh
    ;;
  *)
      lintsh
      lintvim --error
    ;;
esac
