#!/bin/bash

set -oe pipefail

lintsh() {
  echo -e "\nlinting $1 files:"
  files=$(rg -l --no-ignore "^#!.*/$1" ||
    grep -rl --exclude-dir=.git "^#\!.*/$1" . || (
      echo "failed to get files" && exit 1))
  echo "${files}"
  echo "${files}" | xargs shellcheck
}

lintvim() {
  echo -e "\nlinting vim files:"
  files=$(fd -e vim ||
    find . -name "*\.vim" || (
      echo "failed to get files" && exit 1))
  echo "${files}"
  echo "${files}" | xargs vint "$@"
}

case "${LINT:-all}" in
  "vint")
      lintvim
      ;;
  "vint-errors")
      lintvim --error
      ;;
  "shellcheck")
      lintsh sh
      lintsh bash
    ;;
  *)
      lintsh sh
      lintsh bash
      lintvim --error
    ;;
esac
