#!/bin/bash

set -oe pipefail

export DOTFILES_ROOT="${DOTFILES_ROOT:-$(command -v "$0" | xargs dirname)}"
cd "${DOTFILES_ROOT}"
# shellcheck source=/dev/null
source "./script/logging.sh"

grepbang() {
  git -C "${DOTFILES_ROOT}" grep -El "^#!$1" || :
}

lintsh() {
  files=$({
    grepbang ".*/sh"
    grepbang ".*/bash"
    grepbang "/usr/bin/env bash"
    grepbang "/usr/bin/env sh"
  })
  print_run "shell" "$files"
  run "$files" shellcheck
}

lintvim() {
  files=$(git -C "${DOTFILES_ROOT}" ls-files | grep -E "\.vim$" ||
    fail "failed to get vim files")
  print_run "vim" "$files"
  run "$files" vint "$@"
}

print_run() {
  info "linting $1 files ...."
  for i in $(echo -e "$2" | sort -u); do
    debug "linting $i"
  done
}

run() {
  files=$1; shift
  echo "$files" | sort -u | xargs "$@"
  ok "linting $1 files"
}

main() {
  case "${LINT:-all}" in
    "vint")         lintvim ;;
    "vint-errors")  lintvim --error ;;
    "shellcheck")   lintsh ;;
    *)              lintsh; lintvim --error ;;
  esac
}

main || fail "lint failed"
