if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    # For Firefox
    export MOZ_ENABLE_WAYLAND=1
    # For steam
    export SDL_VIDEODRIVER=wayland

    # For Chrome
    export XDG_CURRENT_DESKTOP=sway

    # For fcitx5
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
fi
