name: Docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
    - 'shed/**'
  schedule:
    # https://crontab.guru/#0_7_*_*_1
    - cron:  '0 7 * * 1'

jobs:
  publish:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1
      -
        name: login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        # https://github.com/marketplace/actions/build-and-push-docker-images#customizing
        with:
          context: shed
          push: true
          no-cache: true
          tags: aignas/shed:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
