name: CI

on:
  schedule:
    # https://crontab.guru/#0_7_*_*_1
    - cron:  '0 7 * * 1'

jobs:
  Publish:
    name: Publish docker image
    environment: prod
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        # https://github.com/marketplace/actions/build-and-push-docker-images#customizing
        with:
          context: shed
          push: true
          no-cache: true
          tags: user/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
